sudo: required
services:
  - docker
script:
  - docker build - t lab-app-cloud .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag lab-app-cloud $DOCKER_USER/masterlemon_cloud_exercise
  - docker push $DOCKER_USER/masterlemon_cloud_exercise
